name: Keith Wegner
description: Principal / Bestgate Engineering
url: https://keithwegner.github.io
baseurl: ""
permalink: /:title/

links:
  - label: Company
    url: https://www.bestgateeng.com
  - label: GitHub
    url: https://github.com/keithwegner
  - label: LinkedIn
    url: https://www.linkedin.com/in/keithwegner/

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
